name = "niet-api"
main = "src/index.ts"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
STELLAR_TESTNET_RPC = "https://soroban-testnet.stellar.org"
STELLAR_HORIZON_URL = "https://horizon-testnet.stellar.org"
BASE_SEPOLIA_RPC = "https://sepolia.base.org"
IRIS_SANDBOX_URL = "https://iris-api-sandbox.circle.com"
NIET_SETTLER_ID = "CC3F2ZF7SM6GT7EYWPXULBJWDHNHMYEL3VFJ3A5HRORJ7PHFKNBOWULE"
ORIGIN_SETTLER_ADDRESS = "0x603aba4676a2e51cd12175fc2306991cdc727766"
BASE_SEPOLIA_CCTP_DOMAIN = "6"
STELLAR_CCTP_DOMAIN = "27"
USDC_BASE_SEPOLIA = "0x036CbD53842c5426634e7929541eC2318f3dCF7e"
